
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.eng.t2lab.adap.gatesender.ws.service;





import java.util.List;

import javax.jws.HandlerChain;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import it.eng.t2lab.adap.gatesender.ws.utils.RestSender;
import it.telecomitalia.ec.presentation.EcRequestType;
import it.telecomitalia.ec.presentation.EcResponseType;
import it.telecomitalia.ec.presentation.EcResponseType.EventCrBonus1List;
import it.telecomitalia.ec.presentation.EsitoType;
import it.telecomitalia.ec.presentation.EstrattoConto;
import it.telecomitalia.ec.presentation.EventCrBonus1Type;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-09-03T10:29:16.385+02:00
 * Generated source version: 3.1.12
 * 
 */

//@javax.jws.WebService(
//                      serviceName = "EstrattoContoService",
//                      portName = "EstrattoContoPort",
//                      targetNamespace = "http://telecomitalia.it/ec/presentation",
//                      //wsdlLocation = "file:/C:/tmp/gatesender/conto/EstrattoContoAppImpl.EstrattoContoService.wsdl",
//                      endpointInterface = "it.telecomitalia.ec.presentation.EstrattoConto")

//@HandlerChain(file = "handlers.xml")
@org.apache.cxf.interceptor.OutInterceptors (interceptors = {"it.eng.t2lab.adap.gatesender.ws.config.ComAroundSoapResponceInterceptor" })
@Service
public class EstrattoContoAppImpl implements EstrattoConto {
	
//	@Autowired
//	RestSender restSender;

    
    final static Logger logger = LoggerFactory.getLogger(EstrattoContoAppImpl.class);

    /* (non-Javadoc)
     * @see it.telecomitalia.ec.presentation.EstrattoConto#estrattoConto(it.telecomitalia.ec.presentation.EcRequestType ecRequest)*
     */
    public it.telecomitalia.ec.presentation.EcResponseType estrattoConto(it.telecomitalia.ec.presentation.EcRequestType ecRequest) { 
    	logger.info("Executing operation estrattoConto");
        
    	
//    	EcResponseType response = restSender.send(ecRequest);
    	
		EcResponseType ecResponseType = new EcResponseType();
		ecResponseType .setEsito(EsitoType.OK );
		ecResponseType.setEventCdCNumber(12);
		EventCrBonus1List evBonus1List = new EventCrBonus1List();
		List<EventCrBonus1Type> eventCrBonus1 = evBonus1List.getEventCrBonus1();
		EventCrBonus1Type evBonus1Type = new EventCrBonus1Type();
		evBonus1Type.setBasketName("ciao11");
		eventCrBonus1.add(evBonus1Type );
		ecResponseType.setEventCrBonus1List(evBonus1List );
        
        
        
       return ecResponseType;
    }

}
