<?xml version="1.0" encoding="UTF-8" ?>

<definitions
	xmlns:wssutil="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://telecomitalia.it/ec/presentation" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://telecomitalia.it/ec/presentation"
	name="EstrattoContoService">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://telecomitalia.it/ec/presentation"
				schemaLocation="./EstrattoContoService.xsd" />
		</xsd:schema>
	</types>
	<message name="estrattoConto">
		<part name="parameters" element="tns:estrattoConto" />
	</message>
	<message name="estrattoContoResponse">
		<part name="parameters" element="tns:estrattoContoResponse" />
	</message>
	<portType name="EstrattoConto">
		<operation name="estrattoConto">
			<input
				wsam:Action="http://telecomitalia.it/ec/presentation/EstrattoConto/estrattoContoRequest"
				message="tns:estrattoConto" />
			<output
				wsam:Action="http://telecomitalia.it/ec/presentation/EstrattoConto/estrattoContoResponse"
				message="tns:estrattoContoResponse" />
		</operation>
	</portType>
	<binding name="EstrattoContoPortBinding" type="tns:EstrattoConto">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="estrattoConto">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="EstrattoContoService">
		<port name="EstrattoContoPort" binding="tns:EstrattoContoPortBinding">
			<soap:address
				location="http://localhost:8090/EstrattoContoAppImpl/EstrattoContoService" />
		</port>
	</service>
</definitions>